### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ghost** [loomchild/reload#5]
I have this error :
```
~> reload app.py
```
```
Traceback (most recent call last):
  File "/usr/local/bin/reload", line 7, in <module>
    from reload import main
  File "/usr/local/lib/python2.7/dist-packages/reload.py", line 92
    def reload(*command, ignore_patterns=[]):
                                       ^
SyntaxError: invalid syntax

```

**Comment by loomchild** [comment]
Unfortunately this utility requires Python 3, I haven't ported it to Python 2.
